### ISSUE TITLE
docs: add swagger graphical interface for documentation

### ISSUE THREAD

**Issue by sunkanmii** [Valbou/vtaskr-backend#37]
Hey!

So I noticed the documentation just points to the yaml file and not a visual graphical representation of that yaml file.

I searched the net and found this. Honestly, I don't understand your full code yet, so I can't place anything in it. I'm wondering if you could take a look into this simple stackoverflow solution and see if you could add it to the routes and html views maybe.

Link https://stackoverflow.com/questions/69042448/how-to-generate-openapi-docs-swagger-ui-page-using-static-yaml-file-with-flas

**Comment by Valbou** [comment]
Hello,

OpenAPI v3 is a format you can freely use with Swagger and Postman. There is no need to deploy a graphical representation today with new third party dependencies.

**Comment by sunkanmii** [comment]
Hmmmm.

I see your point. I do feel that if I request for an documentation of any software, I don't want to go directly to just the yaml or json file, it's too raw in that format and not developer-friendly. But, if I see a user interface that I can easily understand and grasp at a glance, I will opt for that instead. 

I tried looking for some examples I saw here, but I've browsed a lot of repositories and somehow I lost them. It's cool though.

Feel free to close this issue then.

**Comment by Valbou** [comment]
I understand, but the API is needed only to make a frontend.
And currently it's not a priority to have a third party integration.

A frontend is already under active development in another git repo : https://github.com/Valbou/vtaskr-frontend
And there is many usage examples. But not ready for production at this stage.
